export const LOAD_CHARACTERS = 'LOAD_CHARACTERS';
export const SET_LOADING = 'SET_LOADING';
export const SEARCH_CHARACTER = 'SEARCH_CHARACTER';
export const GET_CHARACTER = 'GET_CHARACTER';
export const CLEAR_CHARACTER = 'CLEAR_CHARACTER';
export const GET_AVATARS = 'GET_AVATARS';
export const UPDATE_CHARACTERS = 'UPDATE_CHARACTERS';
export const SET_PAGE = 'SET_PAGE';